# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X100cmd < Formula
  desc ""
  homepage ""
  version "1.2.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bellx2/x100cmd/releases/download/v1.2.3/x100cmd_Darwin_arm64.tar.gz"
      sha256 "94caacc870f50a91293985135e4b77c563002482ba19706c76adcee7aed638e8"

      def install
        bin.install "x100cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bellx2/x100cmd/releases/download/v1.2.3/x100cmd_Darwin_x86_64.tar.gz"
      sha256 "f82739ff2b66146a7094b190fc5eff915608a49a4ccf63cecc35b3225ed63a61"

      def install
        bin.install "x100cmd"
      end
    end
  end
end
